<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Data_odp_model extends CI_Model
{

    public $table = 'data_odp';
    public $id = 'id_odp';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        // $this->db->from('data_odp');
        $this->db->join('data_pelanggan','data_odp.id_pelanggan=data_pelanggan.id_pelanggan');
        $this->db->where('data_odp.id_odp', $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_odp', $q);
	// $this->db->or_like('ket_pelanggan', $q);
	// $this->db->or_like('lokasi_pelanggan', $q);
	// $this->db->or_like('nama_pelanggan', $q);
	$this->db->or_like('odp_name', $q);
	$this->db->or_like('otp_slot', $q);
	$this->db->or_like('tgl_pengecekan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    function total_rows_history($q = NULL) {
	$this->db->from('history');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_odp', $q);
	// $this->db->or_like('ket_pelanggan', $q);
	// $this->db->or_like('lokasi_pelanggan', $q);
	// $this->db->or_like('nama_pelanggan', $q);
	$this->db->or_like('odp_name', $q);
	$this->db->or_like('otp_slot', $q);
	$this->db->or_like('tgl_pengecekan', $q);
    $this->db->join('data_pelanggan','data_odp.id_pelanggan=data_pelanggan.id_pelanggan');
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    function print_odp()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_odp');
	// $this->db->or_like('ket_pelanggan');
	// $this->db->or_like('lokasi_pelanggan');
	// $this->db->or_like('nama_pelanggan');
	$this->db->or_like('odp_name');
	$this->db->or_like('otp_slot');
	$this->db->or_like('tgl_pengecekan');
    $this->db->join('data_pelanggan','data_odp.id_pelanggan=data_pelanggan.id_pelanggan');
        return $this->db->get($this->table)->result();
    }

    function get_limit_data_history($limit, $start = 0, $q = NULL) {
        $this->db->order_by('id', $this->order);
	$this->db->limit($limit, $start);
        return $this->db->get('history')->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // delete bulkdata
    function deletebulk(){
        $data = $this->input->post('msg_', TRUE);
        $arr_id = explode(",", $data); 
        $this->db->where_in($this->id, $arr_id);
        return $this->db->delete($this->table);
    }

}

/* End of file Data_odp_model.php */
/* Location: ./application/models/Data_odp_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-07-05 08:19:44 */
/* http://harviacode.com */